name: Deploy via git-ftp
on: 
  push:
    branches: 
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v2
      with:
        url: "ftp://c1690198.ferozo.com/public_html/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
